export const gatherKeys = {
  current_user: ['current_user'],
  current_userList: ['current_userList'],
  templates: ['templates'],
  templates_six: ['templates_six'],
  templates_page: ['templates_page'],
  templates_count: ['templates_count'],
  productsTag: ['productsTag'],
  sian: ['sian'],
  order: ['order'],
  notice: ['notice'],
  question: ['question'],
  qna: ['qna'],
  orderSetting: ['orderSetting'],
  orderItemPreview: ['orderItemPreview'],
  comment: ['comment'],
  categoryList: ['categoryList'],
  mainSlides: ['mainSlides'],
  mainSettingImage: ['mainSettingImage'],
  mainTemplatesCard: ['mainTemplatesCard'],
  //   lists: () => [...todoKeys.all, 'list'],
  //   list: (filters) => [...todoKeys.lists(), { filters }],
  //   details: () => [...todoKeys.all, 'detail'],
  //   detail: (id) => [...todoKeys.details(), id],
};
