const gatherKeys = {
  currentUser: ['currentUser'],
  currentUserList: ['currentUserList'],
  templates: ['templates'],
  templatesTag: ['templatesTag'],
  templatesSix: ['templatesSix'],
  templatesPage: ['templatesPage'],
  templatesCount: ['templatesCount'],
  productsTag: ['productsTag'],
  sian: ['sian'],
  order: ['order'],
  notice: ['notice'],
  question: ['question'],
  qna: ['qna'],
  payment: ['payment'],
  orderSetting: ['orderSetting'],
  orderItemPreview: ['orderItemPreview'],
  comment: ['comment'],
  categoryList: ['categoryList'],
  mainSlides: ['mainSlides'],
  mainSettingImage: ['mainSettingImage'],
  mainTemplatesCard: ['mainTemplatesCard'],
};
export default gatherKeys;
